spring.application.name=cmutem
server.servlet.context-path=/cmutem

spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

#
# Base de datos
#
spring.datasource.url = jdbc:postgresql:utemdb
spring.datasource.username=cm
spring.datasource.password=Utem,2026
spring.jpa.hibernate.ddl-auto=validate

max.distance=1500
